# https://github.com/prometheus-community/helm-charts/pull/626
# These don't seem to be working
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  admin:
    existingSecret: "grafana-admin-credentials"
    userKey: "username"
    passwordKey: "password"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        isDefault: false
  # FIXME: Understand why it's not allowing deployment
  # plugins:
  #   - grafana-piechart-panel
